import type { Job } from "bullmq";
import { prisma } from "../../src/lib/prisma";
import { createJobLogger, serializeError } from "../../src/lib/observability/logger";
import { OPUSCLIP_MAX_ATTEMPTS } from "../../src/lib/queue/video-queue";
import type { VideoProcessingJobData } from "../../src/lib/queue/video-queue";
import { runOpusClipAutomation } from "../../src/lib/opusclip";
import type { OpusClipFailureArtifact } from "../../src/lib/opusclip";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function getSimulationDelayMs() {
  const value = Number(process.env.OPUSCLIP_WORKER_SIMULATION_MS ?? "3000");
  return Number.isFinite(value) && value >= 0 ? value : 3000;
}

function shouldCreateMockClip() {
  return process.env.OPUSCLIP_MOCK_CREATE_CLIP === "true";
}

function getOpusClipFailureArtifact(error: unknown) {
  if (error instanceof Error && error.cause && typeof error.cause === "object") {
    return error.cause as OpusClipFailureArtifact;
  }

  return undefined;
}

export async function processOpusClipVideoJob(job: Job<VideoProcessingJobData>) {
  const { dbJobId, userId, videoId, sourceUrl, sourceStoragePath } = job.data;
  const attempt = job.attemptsMade + 1;
  const maxAttempts = typeof job.opts.attempts === "number" ? job.opts.attempts : OPUSCLIP_MAX_ATTEMPTS;
  const logger = createJobLogger({
    component: "opusclip-worker",
    userId,
    jobId: dbJobId,
  });

  await prisma.job.update({
    where: {
      id: dbJobId,
    },
    data: {
      status: "active",
      attempts: attempt,
      startedAt: new Date(),
      errorMessage: null,
    },
  });

  await prisma.video.update({
    where: {
      id: videoId,
    },
    data: {
      status: "processing_in_opusclip",
      errorMessage: null,
    },
  });

  await logger.info("OpusClip worker started simulated processing.", {
      phase: 2,
      queueJobId: job.id,
      attempt,
      maxAttempts,
      sourceUrl,
      sourceStoragePath,
  });

  try {
    await job.updateProgress(25);
    await sleep(getSimulationDelayMs());

    if (process.env.OPUSCLIP_WORKER_SIMULATE_FAILURE === "true") {
      throw new Error("Simulated OpusClip worker failure.");
    }

    await logger.info("Calling OpusClip Playwright automation skeleton.", {
        phase: 4,
        videoId,
    });

    const automationResult = await runOpusClipAutomation({
      jobId: dbJobId,
      userId,
      videoId,
      sourceUrl,
      sourceStoragePath,
    });

    if (shouldCreateMockClip() && !automationResult.downloadedClips.length && sourceStoragePath) {
      const mockClipId = `mock-${videoId}-1`;
      const existingMockClip = await prisma.clip.findFirst({
        where: {
          videoId,
          userId,
          opusclipClipId: mockClipId,
        },
      });

      if (existingMockClip) {
        await prisma.clip.update({
          where: {
            id: existingMockClip.id,
          },
          data: {
            storagePath: sourceStoragePath,
            title: "Mock clip for local testing",
            caption: "Placeholder output generated by OPUSCLIP_MOCK_CREATE_CLIP for MVP testing.",
            hashtags: ["#test", "#mvp", "#clip"],
            status: "ready_to_upload",
          },
        });
      } else {
        await prisma.clip.create({
          data: {
            videoId,
            userId,
            opusclipClipId: mockClipId,
            storagePath: sourceStoragePath,
            title: "Mock clip for local testing",
            caption: "Placeholder output generated by OPUSCLIP_MOCK_CREATE_CLIP for MVP testing.",
            hashtags: ["#test", "#mvp", "#clip"],
            status: "ready_to_upload",
          },
        });
      }

      await logger.info("Created mock clip record for local testing.", {
          phase: 4,
          videoId,
          sourceStoragePath,
          mockClipId,
      });
    }

    await job.updateProgress(100);

    await prisma.video.update({
      where: {
        id: videoId,
      },
      data: {
        status: "ready_to_upload",
        errorMessage: null,
      },
    });

    await prisma.job.update({
      where: {
        id: dbJobId,
      },
      data: {
        status: "completed",
        attempts: attempt,
        completedAt: new Date(),
        errorMessage: null,
      },
    });

    await logger.info("OpusClip worker completed simulated processing.", {
        phase: 4,
        videoId,
        generatedClipCount: automationResult.clips.length,
        downloadedClipCount: automationResult.downloadedClips.length,
        automationSimulated: automationResult.simulated,
        mockClipCreated: shouldCreateMockClip() && Boolean(sourceStoragePath),
        status: "ready_to_upload",
    });

    return {
      videoId,
      status: "ready_to_upload",
      simulated: true,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Unknown OpusClip worker error.";
    const artifact = getOpusClipFailureArtifact(error);
    const willRetry = attempt < maxAttempts;

    await prisma.video.update({
      where: {
        id: videoId,
      },
      data: {
        status: willRetry ? "queued" : "failed",
        errorMessage,
        retryCount: {
          increment: 1,
        },
      },
    });

    await prisma.job.update({
      where: {
        id: dbJobId,
      },
      data: {
        status: willRetry ? "queued" : "failed",
        attempts: attempt,
        errorMessage,
        completedAt: willRetry ? null : new Date(),
      },
    });

    await logger.error(willRetry ? "OpusClip worker attempt failed; BullMQ will retry." : "OpusClip worker failed after final attempt.", {
        phase: 2,
        attempt,
        maxAttempts,
        willRetry,
        errorMessage,
        error: serializeError(error),
        currentUrl: artifact?.currentUrl,
        screenshotPath: artifact?.screenshotPath,
        errorPath: artifact?.errorPath,
    });

    throw error;
  }
}
